# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
  - task: Docker@2
  inputs:
    containerRegistry: 'hub connection'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: 